### ISSUE TITLE
Update CI to use Solutions & Portable DebugTypes

### ISSUE THREAD

**Issue by carusology** [invio/Invio.Immutable#26]
**Background**
When I created this library with a 1.01 version of the SDK I [set the `DebugType` to `full`](https://github.com/invio/Invio.Immutable/commit/c9c8360dbc47d71723a4da707c2d96900aef7248#diff-d6552f1338597fccd8fc203f214c1930R8) and updated the CI scripts to explicitly reference XML-based `*.csproj` files due to the removal of `global.json` and `project.json`. The `DebugType` really should be `portable` for .NET Core when we pack the code (though it needs to be `full` for when we run opencover on it), and we should add a `*.sln` to manage our `*.csproj` files.

**Task**
* [x] Update the repository to have a `Invio.Immutable.sln` solution at the root of the repository that references the source and test projects.
* [x] Update `Invio.Immutable.csproj` such that `<IsPackable>false</IsPackable>` is specified.
* [x] Restore `set-debug-type.ps1`, but with it updating the `DebugType` via the XML-based `Invio.Immutable.csproj` instead of JSON-based `project.json`.

**Comment by carusology** [comment]
This was resolved in #27
